//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labtask3.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Order
    {
        public int ID { get; set; }
        public int PID { get; set; }
        public int OID { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
